# Generated by Django 3.2.4 on 2021-07-03 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adduserdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adduserdata',
            old_name='addmission_no',
            new_name='admission_no',
        ),
    ]
