# Generated by Django 3.2.4 on 2021-07-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_addmission_no_adduserdata_admission_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduserdata',
            name='admission_no',
            field=models.CharField(max_length=100),
        ),
    ]
