# Generated by Django 3.2.4 on 2021-07-06 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_adduserdata_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adduserdata',
            name='timeStamp',
        ),
        migrations.AddField(
            model_name='adduserdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
